name: release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  PACKAGE_NAME: dlfx
  OWNERS: theodapamede, f10409

permissions:
  id-token: write

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    environment: pypi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
